import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root=path.resolve(process.cwd());
const index=fs.readFileSync(path.join(root,'src/index.ts'),'utf8');
const docker=fs.readFileSync(path.join(root,'Dockerfile'),'utf8');
const db=fs.readFileSync(path.join(root,'src/db.ts'),'utf8');
const migrate=fs.readFileSync(path.join(root,'src/migrate.ts'),'utf8');
const workplace=fs.readFileSync(path.join(root,'src/routes/workplace.ts'),'utf8');
const attendance=fs.readFileSync(path.join(root,'src/routes/attendance.ts'),'utf8');
const leave=fs.readFileSync(path.join(root,'src/routes/leave.ts'),'utf8');
const admin=fs.readFileSync(path.join(root,'src/routes/admin.ts'),'utf8');
const validate=fs.readFileSync(path.join(root,'src/validate.ts'),'utf8');
const dbTest=fs.readFileSync(path.join(root,'test/database-smoke.ts'),'utf8');
const rollback=fs.readFileSync(path.join(root,'../.github/workflows/rollback-production.yml'),'utf8');
const security=fs.readFileSync(path.join(root,'src/security.ts'),'utf8');
const auth=fs.readFileSync(path.join(root,'src/routes/auth.ts'),'utf8');
const sessionMigration=fs.readFileSync(path.join(root,'migrations/002_session_revocation.sql'),'utf8');
const integration=fs.readFileSync(path.join(root,'test/integration.ts'),'utf8');

assert.match(index,/health\/live/);
assert.match(index,/health\/ready/);
assert.match(index,/APP_VERSION/);
assert.match(index,/BUILD_SHA/);
assert.match(index,/X-Request-ID/);
assert.match(index,/GCS_BUCKET/);
assert.match(index,/APP_ORIGIN/);
assert.match(docker,/USER node/);
assert.match(docker,/STOPSIGNAL SIGTERM/);
assert.match(db,/connectTimeout: 10000/);
assert.match(db,/queueLimit: 20/);
assert.match(db,/DB_TRANSACTION_RETRIES/);
assert.match(db,/ER_LOCK_DEADLOCK/);
assert.match(db,/ER_LOCK_WAIT_TIMEOUT/);
assert.match(migrate,/GET_LOCK/);
assert.match(index,/requestTimeout=30000/);
assert.match(index,/headersTimeout=35000/);
assert.match(workplace,/uploadLimiter/);
assert.match(attendance,/attendanceMutationLimiter/);
assert.match(attendance,/verifyOfficeNetwork/);
assert.match(attendance,/OFFICE_NETWORK_IPS/);
assert.doesNotMatch(attendance,/verifyQr|qrToken|'QR'/);
assert.match(leave,/leaveMutationLimiter/);
assert.match(admin,/adminMutationLimiter/);
assert.match(admin,/system-health/);
assert.match(admin,/officeNetwork/);
assert.match(admin,/mysql_version/);
assert.match(validate,/request_id:req.requestId/);
assert.match(validate,/requestId: req.requestId/);
assert.match(dbTest,/schema_migrations/);
assert.match(rollback,/workflow_dispatch/);
assert.match(rollback,/gcloud artifacts docker images describe/);
assert.match(rollback,/gcloud run deploy/);
assert.match(rollback,/Database migrations: not run during rollback/);
assert.match(security,/session_version/);
assert.match(security,/Your session has been revoked/);
assert.match(auth,/session_version/);
assert.match(auth,/AUTH_LOGOUT/);
assert.match(sessionMigration,/ADD COLUMN session_version/);
assert.match(integration,/API integration smoke verification: PASS/);


assert.match(admin,/router\.get\('\/reports\.csv'/);
assert.match(admin,/Content-Type','text\/csv; charset=utf-8/);
assert.match(admin,/Cache-Control','private, no-store/);
assert.match(admin,/\^\[=\+\\-@\\t\\r\]/);
assert.match(admin,/work_minutes_after_fixed_lunch/);
assert.match(admin,/late_threshold/);
assert.match(admin,/fixed_lunch_minutes/);
assert.match(admin,/leave_casual_sl_entitlement/);
assert.match(admin,/leave_earned_entitlement/);
assert.match(admin,/leave_floating_entitlement/);
assert.match(attendance,/late_threshold/);
assert.match(auth,/APP_ORIGIN/);

console.log('Production API contracts: PASS');
